import type { ReactNode } from "react";
import AdBanner from "@site/src/components/AdBanner";
import OriginalLayout from "@theme-original/Layout";
import type { Props } from "@theme/Layout";

// Replace this placeholder with the numeric data-ad-slot value generated by
// AdSense after the site has been approved.
const ADSENSE_BANNER_SLOT = "REPLACE_WITH_AD_UNIT_SLOT_ID";

export default function Layout(props: Props): ReactNode {
  const { children, ...layoutProps } = props;

  return (
    <OriginalLayout {...layoutProps}>
      <AdBanner slot={ADSENSE_BANNER_SLOT} />
      {children}
    </OriginalLayout>
  );
}
